version: '3.8'

services:
  afroo-ai-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: afroo-ai-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - afroo-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  afroo-network:
    external: true
